### PR TITLE
Add user identity

### PR DESCRIPTION
**Pull request by peakxu**
@benedikt, @we5, add support for interacting with [Platform API for user identity]( https://developer.layer.com/docs/platform/users#identity)

### CODE REVIEW

**Comment by benedikt** [comment]
Hi @peakxu! 

Thanks so much for awesome your work on this! I'll look into it and probably merge it soon. 😃 

Cheers,

Benedikt

**Comment by benedikt** [comment]
Hey @peakxu!

I just merged your pull request and made some additional changes, basically removing the need for the explicit `get` call. Please let me know what you think about this and if it works for you!

Again: Thanks a lot for your work! It's very much appreciated :)

Cheers,

Benedikt

**Comment by peakxu** [comment]
@benedikt, looks great to me. Thanks again for the quick review and turnaround.

Any chance you can publish a new version with these changes?

**Comment by benedikt** [comment]
Yes, I'll publish a new version soon!

**Comment by benedikt** [comment]
@peakxu v0.7.0 is out on RubyGems!

**Comment by peakxu** [comment]
@benedikt, awesome. Thank you.

**Pull request merged**
