### PR TITLE
Scope rich content to conversation

### PR DESCRIPTION
**Pull request by peakxu**
@benedikt, please review.

I got a `RestClient::ResourceNotFound: 404 Resource Not Found` when using the existing content API and found that Layer appear to have change their URL structure for Rich Content and nests it under conversation now.

`POST /apps/:app_uuid/conversations/:conversation_uuid/messages`
See https://developer.layer.com/docs/platform/conversations#rich-content

This pull make content uploads work again.

### CODE REVIEW

**Comment by benedikt** [comment]
Hi @peakxu!

Thanks a lot for bringing this up and taking the time to submit a pull request. Unfortunately, I can't merge it because it would break the functionality for the REST API.

I just added some changes to the master branch, that adds the ability to upload rich content via the Platform API: 

```ruby
conversation = Layer::Conversation.find('layer-conversation-id-here')
content = conversation.contents.create('image/png', File.open('photo.png'))
```

Finding rich content works in a similar fashion:

```
conversation = Layer::Conversation.find('layer-conversation-id-here')
content = conversation.contents.find('layer-rich-content-id-here')
```

Hope this helps and thanks again for your efforts! It's highly appreciated. 

Benedikt

**Comment by benedikt** [comment]
@peakxu Sorry, forgot to actually push the code. It's up there now. Please let me know if it works :)

**Comment by peakxu** [comment]
Will give it a whirl, thanks.

**Comment by peakxu** [comment]
Works great, thanks again.

**Pull request closed without merging**
