### PR TITLE
Delete messages

### PR DESCRIPTION
**Pull request by geoffreymm**
Just replicate the same logic to delete messages it was helpful for me. In this case the client must be a authenticated instance as explained [here](https://github.com/benedikt/layer-ruby/pull/8). What do you think?

### CODE REVIEW

**Comment by benedikt** [comment]
Hi @geoffreymm!

Thanks so, so much for this pull request! I really appreciate your effort! :smile: 

Two things that come to my mind:

1) Is there any reason, why you didn't implement `Message#destroy`? 
2) Now that there are two resources having the destroy behavior, maybe having `Operations::Destroy` would be handy.

I'd love to hear your thoughts on this!

Benedikt

**Comment by geoffreymm** [comment]
I made some testes and I was only able to destroy a message with an authenticated client.

**Comment by benedikt** [comment]
The resources keep the client they are initialized with and also pass the client to their relationships. So, given you use an authenticated client to look up the conversation, it will also use the authenticated client to look up messages. 

```
client = Layer::Client.authenticate { |n| ... }
conversation = Layer::Conversation.all(client).first

conversation.messages.all.first.delete # This should work, because it uses the authenticated client
```

**Comment by benedikt** [comment]
Hi @geoffreymm,

I just pushed a new `Operations::Destroy` module, that's now included in both `Conversation` and `Message`. Can you check if it works for your use cases?

Thanks a lot for the work you put into this! 

Cheers,

Benedikt

**Comment by geoffreymm** [comment]
Cool, this is working. Thank you @benedikt! 

Best regards,
Geoff

**Pull request closed without merging**
